// <auto-generated />
namespace net_webform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedate2));
        
        string IMigrationMetadata.Id
        {
            get { return "202307101338426_change-date2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
